// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjb-VaAy2CEPRTm2mXGhIioBOvmiLR67s',
    appId: '1:245861979097:web:34cc0e5748093953ffffc8',
    messagingSenderId: '245861979097',
    projectId: 'mobile-9d0fc',
    authDomain: 'mobile-9d0fc.firebaseapp.com',
    storageBucket: 'mobile-9d0fc.firebasestorage.app',
    measurementId: 'G-DNFZFBEMZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-GECy0RfBBprvkxuZPeua_comE09hIw',
    appId: '1:245861979097:android:be78b68a20a091b1ffffc8',
    messagingSenderId: '245861979097',
    projectId: 'mobile-9d0fc',
    storageBucket: 'mobile-9d0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92TbJaMJAmQ7B4Xtcntz41Ffog7AfUCY',
    appId: '1:245861979097:ios:725728046a5e9dd5ffffc8',
    messagingSenderId: '245861979097',
    projectId: 'mobile-9d0fc',
    storageBucket: 'mobile-9d0fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92TbJaMJAmQ7B4Xtcntz41Ffog7AfUCY',
    appId: '1:245861979097:ios:725728046a5e9dd5ffffc8',
    messagingSenderId: '245861979097',
    projectId: 'mobile-9d0fc',
    storageBucket: 'mobile-9d0fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjb-VaAy2CEPRTm2mXGhIioBOvmiLR67s',
    appId: '1:245861979097:web:391fdc91eda9d570ffffc8',
    messagingSenderId: '245861979097',
    projectId: 'mobile-9d0fc',
    authDomain: 'mobile-9d0fc.firebaseapp.com',
    storageBucket: 'mobile-9d0fc.firebasestorage.app',
    measurementId: 'G-N1Z1XWL05Q',
  );

}